server:
  port: 8080
  address: 192.168.124.6

# webdav检测配置
file-observer:
  boolSort: false  #是否对memory启动 结构化排序

  interval: 5000 #文件夹扫描变动 10小时= 36000000 间隔 此配置也适用于mynote

  consumeTime: 5000  # 消费间隔 处理队列里消息

  targetPic: res/webdav/orderstructfile/pic

  targetMp4: res/webdav/orderstructfile/mp4

  hnotesPath: res/webdav/hnote-data-v2/notes

  hnoteDateMetaPath: res/webdav/hnote-data-v2/meta.json

  obPicAndMp4:  #监听资源的目录
    - res/webdav/img/ #来自PhotoSync
    - res/memory

  taoPath: res/Tao/Tao-and-Teh-zh-cn.md

  gkPath: res/Google Keep

table:
  alltable:
    - mynote

logging:
  file:
    path: res/log

mybatis-plus:
  config-location: classpath:/Mybatis/mybatis-config.xml
  mapper-locations:
    - classpath:/Mybatis/mapper/MyNoteMapper.xml
  global-config:
    db-config:
      update-strategy: not_empty

spring:
  task:
    scheduling:
      pool:
        size: 1   #定时任务线程池大小

  datasource: #数据源配置
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/mydata?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver #mysql的驱动
sync:   # 滞后文件 同步
  file: false
  note: false